name: GEN_NODES

# on: workflow_dispatch
on:
  # schedule:
      # - cron: "0 4,10 * * *"
  workflow_dispatch:
  

jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: szenius/set-timezone@v1.0 # 设置执行环境的时区
        with:
          timezoneLinux: "Asia/Shanghai"
      - uses: actions/setup-python@v5 # 使用python装配器
        with:
          python-version: 3.8
          cache: 'pip'
      - run: pip install -r requirements.txt
      
      - name: Run
        run: |
          python -v
          python Gen.py
          
      - name: Commit
        uses: EndBug/add-and-commit@v4
        with:
          author_name: 
          author_email: 
          message: "Updata"
          add: "*.txt"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
